# Site settings
title: "Agentic AI for Computer Systems Design"
description: "Agentic AI for Full-Stack System Design • CS249r Harvard University Fall 2025"
baseurl: "/cs249r_fall2025"
url: "https://harvard-edge.github.io"
repository: "harvard-edge/cs249r_fall2025"

# Build settings
markdown: kramdown
highlighter: rouge
# Using custom layout instead of theme

# Simple navigation
show_downloads: false

# Course info
instructor: "Vijay Janapa Reddi"
ta: "Chenyu Wang"
semester: "Fall 2025"
course_number: "CS249r"

# Include assets
include:
  - assets/

# Include assets
include:
  - assets/

# Exclude files
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor/
  - arch2-seminar-main/

# Plugins (only GitHub Pages compatible ones)
plugins:
  # - jekyll-feed  # Temporarily commented out due to eventmachine dependency issues
  - jekyll-sitemap
  - jekyll-seo-tag

# Social media and sharing
twitter:
  username: profvjreddi
  card: summary_large_image

social:
  name: "CS249r Harvard"
  links:
    - "https://github.com/harvard-edge/cs249r_fall2025"
    - "https://harvard-edge.github.io/cs249r_fall2025"

# Blog settings
permalink: /blog/:year/:month/:day/:title/

# Comments powered by Disqus
disqus:
  shortname: "architecture2"  # Architecture 2.0: AI Agents for Computing Systems
